// Code generated by vogen DO NOT EDIT.
package sample2

import (
	"testing"
)

type AddressSetter struct {
	Temp *int
}

func BuildAddress(t *testing.T, s *AddressSetter) *Address {
	obj := &Address{}

	if s.Temp == nil {
		obj.Temp = BuildAddressTemp(t)
	} else {
		obj.Temp = *s.Temp
	}

	return obj
}
