// Code generated by vogen DO NOT EDIT.
package sample

import (
	"github.com/tjmtmmnk/vogen/sample2"
)

func NewAddress(number int, number2 int, number2p *AddressNumber, city string, country string, temp sample2.Temp, tempFunc func() int, tempSlice []int, tempSliceP []*int, tempMap map[string]int, temp2 sample2.Temp) (*Address, error) {

	tempVarByVogenNumber, err := NewAddressNumber(number)
	if err != nil {
		return nil, err
	}

	tempVarByVogenNumber2, err := NewAddressNumber2(number2)
	if err != nil {
		return nil, err
	}

	tempVarByVogenCity, err := NewAddressCity(city)
	if err != nil {
		return nil, err
	}

	tempVarByVogenCountry, err := NewAddressCountry(country)
	if err != nil {
		return nil, err
	}

	tempVarByVogenTemp2 := NewAddressTemp2(temp2)

	return &Address{

		// NewAddressNumber
		Number: tempVarByVogenNumber,

		// NewAddressNumber2
		Number2: tempVarByVogenNumber2,

		// NewAddressNumber2p
		Number2p: number2p,

		// NewAddressCity
		City: tempVarByVogenCity,

		// NewAddressCountry
		Country: tempVarByVogenCountry,

		// NewAddressTemp
		Temp: temp,

		// NewAddressTempFunc
		TempFunc: tempFunc,

		// NewAddressTempSlice
		TempSlice: tempSlice,

		// NewAddressTempSliceP
		TempSliceP: tempSliceP,

		// NewAddressTempMap
		TempMap: tempMap,

		// NewAddressTemp2
		Temp2: tempVarByVogenTemp2,
	}, nil
}
