// Code generated by vogen DO NOT EDIT.
package sample

import "testing"

type AddressSetter struct {
	Number *AddressNumber

	Number2 *AddressNumber2

	Number2p *AddressNumber2p

	City *AddressCity

	Country *AddressCountry
}

func BuildAddress(t *testing.T, s *AddressSetter) *Address {
	obj := &Address{}

	if s.Number == nil {
		obj.Number = BuildAddressNumber(t)
	} else {
		obj.Number = *s.Number
	}

	if s.Number2 == nil {
		obj.Number2 = BuildAddressNumber2(t)
	} else {
		obj.Number2 = *s.Number2
	}

	if s.Number2p == nil {
		obj.Number2p = BuildAddressNumber2p(t)
	} else {
		obj.Number2p = *s.Number2p
	}

	if s.City == nil {
		obj.City = BuildAddressCity(t)
	} else {
		obj.City = *s.City
	}

	if s.Country == nil {
		obj.Country = BuildAddressCountry(t)
	} else {
		obj.Country = *s.Country
	}

	return obj
}
