// Code generated by vogen DO NOT EDIT.
package sample

import (
	"time"

	"github.com/tjmtmmnk/vogen/sample2"
)

func NewAddress(number int, number2 int, number2p *AddressNumber, city string, country string, temp sample2.Temp, tempFunc func() int, tempSlice []int, tempSliceP []*int, tempMap map[string]int, temp2 sample2.Temp, tempTime time.Time) (*Address, error) {

	tempVarByVogenNumber, err := NewAddressNumber(number)
	if err != nil {
		return nil, err
	}

	tempVarByVogenNumber2, err := NewAddressNumber2(number2)
	if err != nil {
		return nil, err
	}

	tempVarByVogenCity, err := NewAddressCity(city)
	if err != nil {
		return nil, err
	}

	tempVarByVogenCountry, err := NewAddressCountry(country)
	if err != nil {
		return nil, err
	}

	tempVarByVogenTemp2 := NewAddressTemp2(temp2)

	tempVarByVogenTempTime := NewAddressTempTime(tempTime)

	return &Address{

		Number: tempVarByVogenNumber,

		Number2: tempVarByVogenNumber2,

		Number2p: number2p,

		City: tempVarByVogenCity,

		Country: tempVarByVogenCountry,

		Temp: temp,

		TempFunc: tempFunc,

		TempSlice: tempSlice,

		TempSliceP: tempSliceP,

		TempMap: tempMap,

		Temp2: tempVarByVogenTemp2,

		TempTime: tempVarByVogenTempTime,
	}, nil
}

func NewAddress2(number int) (*Address2, error) {

	tempVarByVogenNumber, err := NewAddress2Number(number)
	if err != nil {
		return nil, err
	}

	return &Address2{

		Number: tempVarByVogenNumber,
	}, nil
}
