// Code generated by vogen DO NOT EDIT.
package sample

func NewAddress(number int, city string, country string) (*Address, error) {

	tempVarByVogen0, err := NewAddressNumber(number)
	if err != nil {
		return nil, err
	}

	tempVarByVogen1, err := NewAddressCity(city)
	if err != nil {
		return nil, err
	}

	tempVarByVogen2, err := NewAddressCountry(country)
	if err != nil {
		return nil, err
	}

	return &Address{

		Number: tempVarByVogen0,

		City: tempVarByVogen1,

		Country: tempVarByVogen2,
	}, nil
}

type rawAddress struct {
	Number int

	City string

	Country string
}

func (d Address) RawValue() rawAddress {
	return rawAddress{

		Number: d.Number.RawValue(),

		City: d.City.RawValue(),

		Country: d.Country.RawValue(),
	}
}

func (d AddressNumber) RawValue() int {
	return int(d)
}

func (d AddressCity) RawValue() string {
	return string(d)
}

func (d AddressCountry) RawValue() string {
	return string(d)
}
