// Code generated by vogen DO NOT EDIT.
package sample

func NewNoFields() *NoFields {

	return &NoFields{}

}

type rawNoFields struct {
}

func (d NoFields) RawValue() rawNoFields {

	return rawNoFields{}
}
