// Code generated by vogen DO NOT EDIT.
package sample

func NewNoFields() (*NoFields, error) {

	return &NoFields{}, nil
}

type rawNoFields struct {
}

func (d NoFields) RawValue() rawNoFields {

	return rawNoFields{}
}
