// Code generated by vogen DO NOT EDIT.
package sample

import "time"

func ParsePerson(name string, age int, catchPhrase *string, createdAt time.Time) (*Person, error) {

	tempVarByVogenName := ParsePersonName(name)

	tempVarByVogenAge := ParsePersonAge(age)

	return &Person{

		Name: tempVarByVogenName,

		Age: tempVarByVogenAge,

		CatchPhrase: catchPhrase,

		CreatedAt: createdAt,
	}, nil
}
