// Code generated by vogen DO NOT EDIT.
package sample

import "time"

func NewPerson(name string, age int, catchPhrase *string, createdAt time.Time) (*Person, error) {

	tempVarByVogen0 := NewPersonName(name)

	tempVarByVogen1 := NewPersonAge(age)

	tempVarByVogen2 := NewPersonCatchphrase(catchPhrase)

	return &Person{

		Name: tempVarByVogen0,

		Age: tempVarByVogen1,

		CatchPhrase: tempVarByVogen2,

		CreatedAt: createdAt,
	}, nil
}

type rawPerson struct {
	Name string

	Age int

	CatchPhrase *string

	CreatedAt time.Time
}

func (d Person) RawValue() rawPerson {

	var tempVarByVogenCatchPhrase *string
	if d.CatchPhrase != nil {
		tempVarByVogenCatchPhrase = (*string)((*string)(d.CatchPhrase))
	}

	return rawPerson{

		Name: d.Name.RawValue(),

		Age: d.Age.RawValue(),

		CatchPhrase: tempVarByVogenCatchPhrase,

		CreatedAt: d.CreatedAt,
	}
}

func (d PersonName) RawValue() string {
	return string(d)
}

func (d PersonAge) RawValue() int {
	return int(d)
}
