// Code generated by vogen DO NOT EDIT.
package sample

import "time"

func ParsePerson(name string, age int, catchPhrase *string, createdAt time.Time) *Person {

	tempVarByVogen0 := ParsePersonName(name)

	tempVarByVogen1 := ParsePersonAge(age)

	tempVarByVogen2 := ParsePersonCatchphrase(catchPhrase)

	return &Person{

		Name: tempVarByVogen0,

		Age: tempVarByVogen1,

		CatchPhrase: tempVarByVogen2,

		CreatedAt: createdAt,
	}

}
