// Code generated by vogen DO NOT EDIT.
package sample

import (
	"testing"
	"time"
)

type PersonSetter struct {
	Name *PersonName

	Age *PersonAge

	CatchPhrase *PersonCatchphrase

	CreatedAt *time.Time

	Temp *Temp
}

func BuildPerson(t *testing.T, s *PersonSetter) *Person {
	obj := &Person{}

	if s.Name == nil {
		obj.Name = BuildPersonName(t)
	} else {
		obj.Name = *s.Name
	}

	if s.Age == nil {
		obj.Age = BuildPersonAge(t)
	} else {
		obj.Age = *s.Age
	}

	if s.CatchPhrase == nil {
		obj.CatchPhrase = BuildPersonCatchphrase(t)
	} else {
		obj.CatchPhrase = *s.CatchPhrase
	}

	if s.CreatedAt == nil {
		obj.CreatedAt = BuildPersonCreatedAt(t)
	} else {
		obj.CreatedAt = *s.CreatedAt
	}

	if s.Temp == nil {
		obj.Temp = BuildTemp(t)
	} else {
		obj.Temp = *s.Temp
	}

	return obj
}
