// Code generated by vogen DO NOT EDIT.
package sample

import "time"

func NewPerson(name string, age int, catchPhrase PersonCatchphrase, createdAt time.Time) (*Person, error) {

	tempVarByVogen0 := NewPersonName(name)

	tempVarByVogen1 := NewPersonAge(age)

	return &Person{

		Name: tempVarByVogen0,

		Age: tempVarByVogen1,

		CatchPhrase: catchPhrase,

		CreatedAt: createdAt,
	}, nil
}

type rawPerson struct {
	Name string

	Age int

	CatchPhrase PersonCatchphrase

	CreatedAt time.Time
}

func (d Person) RawValue() rawPerson {
	return rawPerson{

		Name: d.Name.RawValue(),

		Age: d.Age.RawValue(),

		CatchPhrase: d.CatchPhrase,

		CreatedAt: d.CreatedAt,
	}
}

func (d PersonName) RawValue() string {
	return string(d)
}

func (d PersonAge) RawValue() int {
	return int(d)
}
