// Code generated by vogen DO NOT EDIT.
package sample

import "time"

func ParsePerson(name string, age int, catchPhrase *string, createdAt time.Time, temp int) *Person {

	tempVarByVogenName := ParsePersonName(name)

	tempVarByVogenAge := ParsePersonAge(age)

	tempVarByVogenCatchPhrase := ParsePersonCatchphrase(catchPhrase)

	tempVarByVogenTemp := ParseTemp(temp)

	return &Person{

		Name: tempVarByVogenName,

		Age: tempVarByVogenAge,

		CatchPhrase: tempVarByVogenCatchPhrase,

		CreatedAt: createdAt,

		Temp: tempVarByVogenTemp,
	}
}
